// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "OpenMeteoConfiguration.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class OpenMeteoConfiguration
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Datasource Extension/
// User:        SuperUser Account
namespace AppCode.Data
{
  // This is a generated class for OpenMeteoConfiguration 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// OpenMeteoConfiguration data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Current`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class OpenMeteoConfiguration: AutoGenerated.ZAutoGenOpenMeteoConfiguration
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'OpenMeteoConfiguration' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenOpenMeteoConfiguration: Custom.Data.CustomItem
  {
    /// <summary>
    /// Current as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Current", scrubHtml: true) etc.
    /// </summary>
    public string Current => _item.String("Current", fallback: "");

    /// <summary>
    /// ForecastDays as int. <br/>
    /// To get other types use methods such as .Decimal("ForecastDays")
    /// </summary>
    public int ForecastDays => _item.Int("ForecastDays");

    /// <summary>
    /// Hourly as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Hourly", scrubHtml: true) etc.
    /// </summary>
    public string Hourly => _item.String("Hourly", fallback: "");

    /// <summary>
    /// Latitude as int. <br/>
    /// To get other types use methods such as .Decimal("Latitude")
    /// </summary>
    public int Latitude => _item.Int("Latitude");

    /// <summary>
    /// Longitude as int. <br/>
    /// To get other types use methods such as .Decimal("Longitude")
    /// </summary>
    public int Longitude => _item.Int("Longitude");

    /// <summary>
    /// Timezone as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Timezone", scrubHtml: true) etc.
    /// </summary>
    public string Timezone => _item.String("Timezone", fallback: "");
  }
}